#!/usr/bin/env php
<?php

// Start the journey

use App\Core\CLI\Command;

define('ZERO_START', microtime(true));
define('ROOT_DIR', __DIR__);
define('DS', DIRECTORY_SEPARATOR);


// Load the autoloader
if (file_exists('./vendor/autoload.php')) {
    // Load the composer autoloader
    require_once './vendor/autoload.php';
} else {
    // Load the bootstrap files
    require_once './app/Core/functions.php';
    // Load the custom autoloader
    require_once './app/Core/Autoloader.php';

    // Register the autoloader
    Autoloader::setPath(ROOT_DIR . '/app/');
    spl_autoload_register('Autoloader::loader');
}


/**
 * Start the command line listener
 * 
 * @return void
 */
(new Command())->listener();
